# Generated by Django 2.2.5 on 2019-10-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commnet',
            name='target',
            field=models.CharField(max_length=100, verbose_name='评论目标'),
        ),
    ]
